apiVersion: v1
data:
  ConnectionStrings__podcasts: U2VydmVyPXNlcnZlciw2MjExNTtVc2VyIElEPXNhO1Bhc3N3b3JkPURvbWV0cmFpbiMxMjM7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT10cnVlO0luaXRpYWwgQ2F0YWxvZz1wb2RjYXN0cw==
kind: Secret
metadata:
  annotations: {}
  labels:
    app: api
  name: api
type: Opaque