apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: ratingservice
  name: ratingservice
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: ratingservice
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: ratingservice
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: ratingservice
        - secretRef:
            name: ratingservice
        image: '{{ .Values.images.ratingservice }}'
        imagePullPolicy: IfNotPresent
        name: ratingservice
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
      terminationGracePeriodSeconds: 180