apiVersion: v1
data:
  ConnectionStrings__cache: Y2FjaGU6NjM3OSxwYXNzd29yZD1tSHFTYjJSckFnTk9ybnBvaTFuTERR
kind: Secret
metadata:
  annotations: {}
  labels:
    app: ratingservice
  name: ratingservice
type: Opaque