apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: server
  name: server
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: server
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: server
        - secretRef:
            name: server
        image: '{{ .Values.images.server }}'
        imagePullPolicy: IfNotPresent
        name: server
        ports:
        - containerPort: 1433
          name: tcp
      terminationGracePeriodSeconds: 180