apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: server
  name: server
spec:
  ports:
  - name: tcp
    port: 1433
    targetPort: 62115
  selector:
    app: server
  type: ClusterIP