apiVersion: v1
data:
  ACCEPT_EULA: "Y"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889
  OTEL_SERVICE_NAME: server
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: server
  name: server